# Generated by Django 2.2.3 on 2019-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_viewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='snack',
            field=models.CharField(choices=[('p', 'With Popcorn'), ('c', 'With Candy'), ('i', 'With Ice Cream'), ('c', 'With Chips'), ('s', 'With Steak')], default='p', max_length=50),
        ),
    ]
