# Generated by Django 2.2.3 on 2019-09-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190912_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='viewing',
            name='date',
            field=models.DateField(verbose_name='Viewing Date'),
        ),
    ]
